[supervisord]
nodaemon=true
logfile=/tmp/supervisord.log

[program:vigilante]
command=python vigilante.py
environment=AUREA_FALLAR="1"
autorestart=unexpected
startsecs=0
startretries=3
stdout_logfile=/tmp/vigilante.log
