// El contrato gRPC de pricing (G10, Fase 23). Es la misma pregunta que GET /prices/{sku}?store= del OpenAPI,
// en binario y por HTTP/2: la usa inventory en la venta. El OpenAPI sigue siendo el contrato de lo demás.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.31.1
// source: pricing/v1/pricing.proto

package pricingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`     // SKU-0000
	Store         string                 `protobuf:"bytes,2,opt,name=store,proto3" json:"store,omitempty"` // DRO-000
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPriceRequest) Reset() {
	*x = GetPriceRequest{}
	mi := &file_pricing_v1_pricing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPriceRequest) ProtoMessage() {}

func (x *GetPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_v1_pricing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPriceRequest.ProtoReflect.Descriptor instead.
func (*GetPriceRequest) Descriptor() ([]byte, []int) {
	return file_pricing_v1_pricing_proto_rawDescGZIP(), []int{0}
}

func (x *GetPriceRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *GetPriceRequest) GetStore() string {
	if x != nil {
		return x.Store
	}
	return ""
}

type Price struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Store         string                 `protobuf:"bytes,2,opt,name=store,proto3" json:"store,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`      // en pesos, sin decimales
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"` // COP
	RegulatedCap  *int64                 `protobuf:"varint,5,opt,name=regulated_cap,json=regulatedCap,proto3,oneof" json:"regulated_cap,omitempty"`
	Capped        bool                   `protobuf:"varint,6,opt,name=capped,proto3" json:"capped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Price) Reset() {
	*x = Price{}
	mi := &file_pricing_v1_pricing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Price) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Price) ProtoMessage() {}

func (x *Price) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_v1_pricing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Price.ProtoReflect.Descriptor instead.
func (*Price) Descriptor() ([]byte, []int) {
	return file_pricing_v1_pricing_proto_rawDescGZIP(), []int{1}
}

func (x *Price) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *Price) GetStore() string {
	if x != nil {
		return x.Store
	}
	return ""
}

func (x *Price) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Price) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Price) GetRegulatedCap() int64 {
	if x != nil && x.RegulatedCap != nil {
		return *x.RegulatedCap
	}
	return 0
}

func (x *Price) GetCapped() bool {
	if x != nil {
		return x.Capped
	}
	return false
}

var File_pricing_v1_pricing_proto protoreflect.FileDescriptor

const file_pricing_v1_pricing_proto_rawDesc = "" +
	"\n" +
	"\x18pricing/v1/pricing.proto\x12\x0elab.pricing.v1\"9\n" +
	"\x0fGetPriceRequest\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x14\n" +
	"\x05store\x18\x02 \x01(\tR\x05store\"\xb5\x01\n" +
	"\x05Price\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x14\n" +
	"\x05store\x18\x02 \x01(\tR\x05store\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12(\n" +
	"\rregulated_cap\x18\x05 \x01(\x03H\x00R\fregulatedCap\x88\x01\x01\x12\x16\n" +
	"\x06capped\x18\x06 \x01(\bR\x06cappedB\x10\n" +
	"\x0e_regulated_cap2M\n" +
	"\aPricing\x12B\n" +
	"\bGetPrice\x12\x1f.lab.pricing.v1.GetPriceRequest\x1a\x15.lab.pricing.v1.PriceB6\n" +
	"\x1bco.coodrosan.lab.pricing.v1P\x01Z\x15lab/pricing/pricingv1b\x06proto3"

var (
	file_pricing_v1_pricing_proto_rawDescOnce sync.Once
	file_pricing_v1_pricing_proto_rawDescData []byte
)

func file_pricing_v1_pricing_proto_rawDescGZIP() []byte {
	file_pricing_v1_pricing_proto_rawDescOnce.Do(func() {
		file_pricing_v1_pricing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pricing_v1_pricing_proto_rawDesc), len(file_pricing_v1_pricing_proto_rawDesc)))
	})
	return file_pricing_v1_pricing_proto_rawDescData
}

var file_pricing_v1_pricing_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pricing_v1_pricing_proto_goTypes = []any{
	(*GetPriceRequest)(nil), // 0: lab.pricing.v1.GetPriceRequest
	(*Price)(nil),           // 1: lab.pricing.v1.Price
}
var file_pricing_v1_pricing_proto_depIdxs = []int32{
	0, // 0: lab.pricing.v1.Pricing.GetPrice:input_type -> lab.pricing.v1.GetPriceRequest
	1, // 1: lab.pricing.v1.Pricing.GetPrice:output_type -> lab.pricing.v1.Price
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pricing_v1_pricing_proto_init() }
func file_pricing_v1_pricing_proto_init() {
	if File_pricing_v1_pricing_proto != nil {
		return
	}
	file_pricing_v1_pricing_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pricing_v1_pricing_proto_rawDesc), len(file_pricing_v1_pricing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pricing_v1_pricing_proto_goTypes,
		DependencyIndexes: file_pricing_v1_pricing_proto_depIdxs,
		MessageInfos:      file_pricing_v1_pricing_proto_msgTypes,
	}.Build()
	File_pricing_v1_pricing_proto = out.File
	file_pricing_v1_pricing_proto_goTypes = nil
	file_pricing_v1_pricing_proto_depIdxs = nil
}
