-- Esquema en Postgres (G3): lo aplica el Job de migraciones (`java -jar … migrate`), no el arranque.
-- Idempotente: todo es IF NOT EXISTS. Lo único distinto de SQLite es cómo se numeran los movimientos.
CREATE TABLE IF NOT EXISTS stock_levels (
    store             TEXT    NOT NULL,
    sku               TEXT    NOT NULL,
    quantity          INTEGER NOT NULL CHECK (quantity >= 0),
    reorder_threshold INTEGER NOT NULL DEFAULT 0 CHECK (reorder_threshold >= 0),
    PRIMARY KEY (store, sku)
);

-- La existencia solo cambia por movimientos (D33): la suma de quantity es la existencia.
CREATE TABLE IF NOT EXISTS stock_movements (
    id          BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store       TEXT    NOT NULL,
    sku         TEXT    NOT NULL,
    type        TEXT    NOT NULL,
    quantity    INTEGER NOT NULL,
    reason_code TEXT,
    reference   TEXT,
    created_at  TEXT    NOT NULL
);

-- Una tabla de datos, no un enum del contrato: se agregan códigos sin cambiar el OpenAPI.
CREATE TABLE IF NOT EXISTS reason_codes (
    code        TEXT    PRIMARY KEY,
    description TEXT    NOT NULL,
    applies_to  TEXT    NOT NULL,
    active      INTEGER NOT NULL DEFAULT 1
);

-- G5: las ventas. Cada una deja además un movimiento SALE en stock_movements.
CREATE TABLE IF NOT EXISTS sales (
    id          BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store       TEXT    NOT NULL,
    sku         TEXT    NOT NULL,
    quantity    INTEGER NOT NULL CHECK (quantity >= 1),
    unit_price  INTEGER NOT NULL,
    total       INTEGER NOT NULL,
    created_at  TEXT    NOT NULL
);

-- G11: el préstamo entre droguerías como saga. Una fila por préstamo, con el estado de la saga, y una
-- por cada paso hecho o deshecho: el registro que deja retomar una saga a medias.
CREATE TABLE IF NOT EXISTS loans (
    id                     BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku                    TEXT    NOT NULL,
    origin_store           TEXT    NOT NULL,
    destination_store      TEXT    NOT NULL,
    quantity               INTEGER NOT NULL CHECK (quantity >= 1),
    status                 TEXT    NOT NULL,
    sale_id                TEXT,
    replenishment_order_id TEXT,
    failure                TEXT,
    created_at             TEXT    NOT NULL,
    updated_at             TEXT    NOT NULL
);

CREATE TABLE IF NOT EXISTS loan_steps (
    id      BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_id BIGINT  NOT NULL,
    step    TEXT    NOT NULL,
    action  TEXT    NOT NULL,
    outcome TEXT    NOT NULL,
    detail  TEXT,
    at      TEXT    NOT NULL
);

-- G13 (Fase 26): la clave de idempotencia de la venta y del préstamo. Única cuando está: la misma clave es la
-- misma operación. Las ventas y los préstamos de antes de G13 no tienen clave.
ALTER TABLE sales ADD COLUMN IF NOT EXISTS idempotency_key TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS sales_idempotency_key ON sales (idempotency_key) WHERE idempotency_key IS NOT NULL;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS idempotency_key TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS loans_idempotency_key ON loans (idempotency_key) WHERE idempotency_key IS NOT NULL;

-- G13: el outbox. El evento se escribe aquí, en la misma transacción que la venta; el sidecar outbox-relay lo
-- publica en NATS y le pone published_at. Si nadie lo publicó, sigue aquí: nada se pierde entre el commit y el bus.
CREATE TABLE IF NOT EXISTS outbox (
    id           TEXT PRIMARY KEY,
    subject      TEXT NOT NULL,
    payload      TEXT NOT NULL,
    created_at   TEXT NOT NULL,
    published_at TEXT
);
CREATE INDEX IF NOT EXISTS outbox_pending ON outbox (created_at) WHERE published_at IS NULL;
