# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: evento.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'evento.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x65vento.proto\x12\raurea.eventos\"U\n\x06\x45vento\x12\x0c\n\x04\x63ita\x18\x01 \x01(\x03\x12\x0c\n\x04sede\x18\x02 \x01(\t\x12\x0c\n\x04tipo\x18\x03 \x01(\t\x12\x12\n\nmomento_ms\x18\x04 \x01(\x03\x12\r\n\x05valor\x18\x05 \x01(\x03\".\n\x04Lote\x12&\n\x07\x65ventos\x18\x01 \x03(\x0b\x32\x15.aurea.eventos.Eventob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'evento_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVENTO']._serialized_start=31
  _globals['_EVENTO']._serialized_end=116
  _globals['_LOTE']._serialized_start=118
  _globals['_LOTE']._serialized_end=164
# @@protoc_insertion_point(module_scope)
