import { Injectable, OnModuleDestroy } from '@nestjs/common';
import { DatabaseSync } from 'node:sqlite';
import { join } from 'node:path';
import pg from 'pg';
import { logLine } from './logger.js';

// El almacén de replenish (G3): Postgres si hay DATABASE_URL, y si no, el SQLite que trae Node (G1),
// que sigue siendo el de compose. Las consultas se escriben con `?`; para Postgres se numeran ($1, $2…).
const usePostgres = Boolean(process.env.DATABASE_URL);

// El esquema de cada motor. Lo único distinto es cómo se numeran las órdenes. Idempotente.
const SCHEMA = (postgres: boolean) => `
  CREATE TABLE IF NOT EXISTS replenishment_orders (
    seq                ${postgres ? 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY' : 'INTEGER PRIMARY KEY AUTOINCREMENT'},
    sku                TEXT    NOT NULL,
    destination_store  TEXT    NOT NULL,
    origin_store       TEXT,
    quantity           INTEGER NOT NULL CHECK (quantity >= 1),
    status             TEXT    NOT NULL DEFAULT 'PENDING',
    cancel_reason_code TEXT,
    replaces_order_id  TEXT,
    -- G12 (Fase 25): el aviso que la creó, cuando la crea un evento y no una petición.
    source_event_id    TEXT,
    -- G13 (Fase 26): la clave con que se pidió; dos pedidos con la misma clave son la misma orden.
    idempotency_key    TEXT
  );${postgres ? `
  ALTER TABLE replenishment_orders ADD COLUMN IF NOT EXISTS source_event_id TEXT;
  ALTER TABLE replenishment_orders ADD COLUMN IF NOT EXISTS idempotency_key TEXT;` : ''}
  CREATE UNIQUE INDEX IF NOT EXISTS replenishment_orders_idempotency_key
    ON replenishment_orders (idempotency_key) WHERE idempotency_key IS NOT NULL;
  -- G13: los eventos ya procesados, por su eventId. Es la tabla de "archivos procesados" de la Braqui, con la
  -- clave correcta: el hecho, no el nombre del sobre en que llegó.
  CREATE TABLE IF NOT EXISTS processed_events (
    event_id     TEXT PRIMARY KEY,
    order_id     TEXT,
    processed_at TEXT NOT NULL
  );
  -- Una tabla de datos, no un enum del contrato: se agregan códigos sin cambiar el OpenAPI.
  CREATE TABLE IF NOT EXISTS reason_codes (
    code        TEXT    PRIMARY KEY,
    description TEXT    NOT NULL,
    active      INTEGER NOT NULL DEFAULT 1
  );
  INSERT INTO reason_codes (code, description) VALUES
    ('CREATED_BY_MISTAKE', 'La orden se creó por error'),
    ('WRONG_QUANTITY',     'La cantidad pedida no era la que se necesitaba'),
    ('WRONG_STORE',        'La droguería de origen o de destino no era esa'),
    ('NO_LONGER_NEEDED',   'La droguería ya no necesita el producto'),
    -- G11 (Fase 24): la saga del préstamo cancela con este código la moto que ya no tiene qué llevar.
    ('SAGA_COMPENSATION',  'Compensación de una saga: un paso posterior falló')
  ON CONFLICT (code) DO NOTHING;
`;

const numbered = (sql: string) => {
  let i = 0;
  return sql.replace(/\?/g, () => `$${++i}`);
};

@Injectable()
export class Store implements OnModuleDestroy {
  private readonly sqlite?: DatabaseSync;
  private readonly pool?: pg.Pool;
  readonly engine = usePostgres ? 'postgres' : 'sqlite';

  constructor() {
    if (usePostgres) {
      // G4: dos segundos para conectarse; sin el límite, pg espera lo que tarde la red en rendirse.
      this.pool = new pg.Pool({ connectionString: process.env.DATABASE_URL, max: 5, connectionTimeoutMillis: 2000 });
      // G4: si la base corta una conexión que estaba quieta en el pool, pg emite 'error' en el pool. Sin
      // este manejador, Node lo trata como una excepción no atendida y el proceso muere (Fase 15).
      this.pool.on('error', (e) => logLine('WARN', 'conexión del pool perdida', { error: e.message }));
    } else {
      const dir = process.env.DATA_DIR ?? '/var/lib/replenish';
      this.sqlite = new DatabaseSync(join(dir, 'replenish.db'));
      // Con SQLite, el esquema se crea al arrancar, como en G1. Con Postgres, no: lo crea el Job, antes.
      this.sqlite.exec(SCHEMA(false));
      // G12 y G13: SQLite no tiene ADD COLUMN IF NOT EXISTS; en una base anterior, las columnas se agregan aquí.
      for (const column of ['source_event_id', 'idempotency_key']) {
        try {
          this.sqlite.exec(`ALTER TABLE replenishment_orders ADD COLUMN ${column} TEXT`);
        } catch {
          // ya existía
        }
      }
    }
  }

  // Las filas de una consulta, con la misma forma en los dos motores.
  async all<T>(sql: string, ...params: (string | number | null)[]): Promise<T[]> {
    if (this.pool) return (await this.pool.query(numbered(sql), params)).rows as T[];
    return this.sqlite!.prepare(sql).all(...params) as unknown as T[];
  }

  async one<T>(sql: string, ...params: (string | number | null)[]): Promise<T | undefined> {
    return (await this.all<T>(sql, ...params))[0];
  }

  // G13: varias consultas en una transacción. Con Postgres, una conexión del pool para todas; con SQLite, la única.
  async transaction<T>(work: (one: <R>(sql: string, ...params: (string | number | null)[]) => Promise<R | undefined>) => Promise<T>): Promise<T> {
    if (!this.pool) {
      this.sqlite!.exec('BEGIN');
      try {
        const result = await work(async <R>(sql: string, ...params: (string | number | null)[]) =>
          this.sqlite!.prepare(sql).all(...params)[0] as unknown as R | undefined);
        this.sqlite!.exec('COMMIT');
        return result;
      } catch (e) {
        this.sqlite!.exec('ROLLBACK');
        throw e;
      }
    }
    const client = await this.pool.connect();
    try {
      await client.query('BEGIN');
      const result = await work(async <R>(sql: string, ...params: (string | number | null)[]) =>
        (await client.query(numbered(sql), params)).rows[0] as R | undefined);
      await client.query('COMMIT');
      return result;
    } catch (e) {
      await client.query('ROLLBACK');
      throw e;
    } finally {
      client.release();
    }
  }

  // La readiness (G4): un `select 1` que no puede tardar más de `ms`.
  async ping(ms: number): Promise<void> {
    if (!this.pool) {
      this.sqlite!.prepare('select 1').get();
      return;
    }
    let timer: NodeJS.Timeout | undefined;
    const timeout = new Promise<never>((_, reject) => {
      timer = setTimeout(() => reject(new Error(`sin respuesta en ${ms} ms`)), ms);
    });
    try {
      await Promise.race([this.pool.query('select 1'), timeout]);
    } finally {
      clearTimeout(timer);
    }
  }

  // `node dist/migrate.js`: el Job de migraciones (G3).
  async migrate(): Promise<void> {
    if (this.pool) await this.pool.query(SCHEMA(true));
    else this.sqlite!.exec(SCHEMA(false));
  }

  async onModuleDestroy() {
    await this.pool?.end();
  }
}
