<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2"
           xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2"
           targetNamespace="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2"
           elementFormDefault="qualified">
  <xs:import namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2"
             schemaLocation="cbc-minimo.xsd"/>
  <xs:import namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2"
             schemaLocation="cac-minimo.xsd"/>
  <xs:element name="Invoice">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="cbc:ID"/>
        <xs:element ref="cbc:IssueDate"/>
        <xs:element ref="cac:AccountingSupplierParty"/>
        <xs:element ref="cac:InvoiceLine" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
