# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agenda.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'agenda.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x61genda.proto\x12\x0c\x61urea.agenda\".\n\x0bSedeRequest\x12\x0c\n\x04sede\x18\x01 \x01(\t\x12\x11\n\tdemora_ms\x18\x02 \x01(\x05\"-\n\x0e\x44isponibilidad\x12\x0c\n\x04sede\x18\x01 \x01(\t\x12\r\n\x05horas\x18\x02 \x03(\t\";\n\nEventoCita\x12\x0c\n\x04sede\x18\x01 \x01(\t\x12\x0c\n\x04tipo\x18\x02 \x01(\t\x12\x11\n\tsecuencia\x18\x03 \x01(\x05\x32\xa4\x01\n\x06\x41genda\x12R\n\x17\x43onsultarDisponibilidad\x12\x19.aurea.agenda.SedeRequest\x1a\x1c.aurea.agenda.Disponibilidad\x12\x46\n\rEventosDeSede\x12\x19.aurea.agenda.SedeRequest\x1a\x18.aurea.agenda.EventoCita0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agenda_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEDEREQUEST']._serialized_start=30
  _globals['_SEDEREQUEST']._serialized_end=76
  _globals['_DISPONIBILIDAD']._serialized_start=78
  _globals['_DISPONIBILIDAD']._serialized_end=123
  _globals['_EVENTOCITA']._serialized_start=125
  _globals['_EVENTOCITA']._serialized_end=184
  _globals['_AGENDA']._serialized_start=187
  _globals['_AGENDA']._serialized_end=351
# @@protoc_insertion_point(module_scope)
