apiVersion: v1
kind: Service
metadata:
  name: orders-java
  labels:
    app: orders-java
spec:
  type: ClusterIP
  selector:
    app: orders-java
    release: {{ .Release.Name }}
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
