#!/usr/bin/env bash
# Copies the source files the carta session wrote under the unversioned salidas/ of its own zz-code
# directory into 05-carta-codigo/, so they are versioned. Only code and build files: no outputs,
# keys, binaries, Cython-generated .c, downloaded runtimes (jv03/graalpy) or generated trees (mutants, .venv, dist, the airflow-home that Airflow writes...).
# Re-running replaces 05-carta-codigo/ with a fresh copy.
set -euo pipefail
AQUI="$(cd "$(dirname "$0")" && pwd)"
CARTA="$AQUI/../python-for-java-devs-20261005-f516/salidas"
DEST="${DEST:-$AQUI/05-carta-codigo}"   # DEST lets regenerar-rescates.py --comprobar write elsewhere
rm -rf "$DEST"
mkdir -p "$DEST"
cd "$CARTA"
find . -type d \( -name graalpy -o -name mutants -o -name .venv -o -name venv -o -name dist -o -name build \
       -o -name target -o -name node_modules -o -name __pycache__ -o -name .pytest_cache -o -name .hypothesis \
       -o -name .mypy_cache -o -name .ruff_cache -o -name airflow-home \) -prune -o -type f \( \
       -name '*.py' -o -name '*.pyx' -o -name '*.sh' -o -name '*.c' -o -name '*.cpp' -o -name '*.rs' \
       -o -name '*.toml' -o -name '*.java' -o -name '*.kt' -o -name '*.go' -o -name '*.js' -o -name '*.ts' \
       -o -name '*.yml' -o -name '*.yaml' -o -name '*.sql' -o -name '*.j2' -o -name '*.jinja' -o -name '*.html' \
       -o -name '*.proto' -o -name '*.xml' -o -name '*.typ' -o -name '*.cfg' -o -name '*.ini' -o -name '*.properties' \
       -o -name 'Dockerfile*' -o -name 'Makefile' -o -name 'CMakeLists.txt' -o -name 'requirements*.txt' \) -print \
  | sort | while read -r f; do
      # Cython writes its .c next to the .pyx: generated, not authored
      head -c 200 "$f" | grep -q "Generated by Cython" && continue
      mkdir -p "$DEST/$(dirname "$f")"
      cp -p "$f" "$DEST/$f"
    done
echo "$(find "$DEST" -type f | wc -l | tr -d ' ') archivos copiados a $DEST"
