"""La lista única de la carta: track, nombre del track y secciones (slug, título). De aquí sale la
numeración opNNN del plan. Orden = propuesta §19 con las fusiones aplicadas (guía §14.3)."""
CARTA = [
 ("lg", "Legado e intercambio sectorial", [
  ("ancho-fijo-y-mainframe", "Ancho fijo y mainframe"),
  ("xml-en-serio", "XML en serio"),
  ("documentos-firmados", "Documentos firmados"),
  ("edi", "EDI: X12 y EDIFACT"),
  ("hl7-y-fhir", "Salud: HL7 v2 y FHIR"),
  ("archivos-planos-hostiles", "Archivos planos hostiles"),
  ("veredicto", "Veredicto: escribir el parser o comprarlo")]),
 ("au", "Automatización externa", [
  ("http-contra-sistemas-ajenos", "HTTP contra sistemas ajenos"),
  ("scraping", "Scraping y su fragilidad"),
  ("playwright", "Playwright y los portales sin API"),
  ("ssh-y-sistemas-remotos", "SSH y sistemas remotos"),
  ("apis-de-saas", "APIs de SaaS y su OAuth"),
  ("desplegar-automatizaciones", "Desplegar automatizaciones"),
  ("veredicto", "Veredicto: la automatización que se rompe sola")]),
 ("co", "Comunicaciones y transferencia", [
  ("correo-saliente", "Correo saliente"),
  ("que-el-correo-llegue", "Que el correo llegue"),
  ("correo-entrante", "Correo entrante"),
  ("probar-correo", "Probar correo sin mandarlo"),
  ("transferencia-de-archivos", "Transferencia de archivos"),
  ("mensajeria", "Mensajería y notificaciones"),
  ("veredicto", "Veredicto: qué protocolo para qué")]),
 ("wf", "Orquestación de trabajos y flujos", [
  ("el-eje", "El eje: de cron al flujo durable"),
  ("colas-de-tareas", "Colas de tareas"),
  ("programacion-en-proceso", "Programación en proceso"),
  ("airflow", "Airflow: el grafo declarativo"),
  ("prefect-y-dagster", "Prefect, Dagster y el asset"),
  ("temporal", "Temporal: flujos durables"),
  ("lo-transversal", "Idempotencia, reanudación y backfill"),
  ("veredicto", "Veredicto: el cierre nocturno en cuatro orquestadores")]),
 ("qa", "Calidad, pruebas y mantenimiento", [
  ("la-piramide-para-uno", "La pirámide para un equipo de uno"),
  ("pytest-a-fondo", "pytest a fondo"),
  ("dobles-y-datos", "Dobles y datos de prueba"),
  ("integracion-de-verdad", "Integración de verdad con testcontainers"),
  ("propiedades-y-modelos", "Propiedades y modelos con Hypothesis"),
  ("medir-la-suite", "Medir la suite: cobertura y mutación"),
  ("carga-y-rendimiento", "Carga y rendimiento"),
  ("la-cadena-de-calidad", "La cadena de calidad"),
  ("e2e-con-playwright", "Pruebas e2e con Playwright"),
  ("veredicto", "Veredicto: qué vale la pena cuando eres uno")]),
 ("ob", "Observar el sistema propio", [
  ("las-senales", "Las señales y los eventos anchos"),
  ("bitacoras", "Bitácoras"),
  ("metricas", "Métricas"),
  ("trazas", "Trazas con OpenTelemetry"),
  ("perfilado-en-produccion", "Perfilado en producción"),
  ("errores-como-producto", "Errores como producto"),
  ("veredicto", "Veredicto: el presupuesto de observabilidad")]),
 ("se", "Seguridad aplicada y criptografía", [
  ("el-modelo", "El modelo: qué pregunta contesta cada primitiva"),
  ("cryptography-y-pynacl", "cryptography y PyNaCl"),
  ("contrasenas-y-tokens", "Contraseñas y tokens"),
  ("identidad-delegada", "Identidad delegada: OAuth2 y OIDC"),
  ("secretos", "Secretos en reposo y en tránsito"),
  ("tls-de-verdad", "TLS de verdad"),
  ("defensa-de-la-aplicacion", "Defensa de la aplicación"),
  ("veredicto", "Veredicto: qué implementar y qué dejar de implementar")]),
 ("tx", "Texto, plantillas y documentación", [
  ("el-eje", "El eje: concatenar, formatear, plantilla, árbol"),
  ("jinja2-a-fondo", "Jinja2 a fondo"),
  ("las-otras-plantillas", "Las otras plantillas"),
  ("codigo-como-dato", "Colorear y entender código"),
  ("markdown", "Markdown y su ecosistema"),
  ("documentacion", "Documentación como producto"),
  ("generacion-de-codigo", "Generación de código y andamiaje"),
  ("texto-dificil", "Texto difícil: Unicode e internacionalización"),
  ("veredicto", "Veredicto: plantilla o lenguaje mal hecho")]),
 ("ui", "Interfaces y entregables sin frontend", [
  ("el-modelo-y-su-costo", "El modelo y su costo"),
  ("gradio", "Gradio"),
  ("streamlit", "Streamlit y su re-ejecución"),
  ("dash", "Dash y los callbacks"),
  ("nicegui-y-compania", "NiceGUI y compañía"),
  ("marimo", "marimo: el notebook que es una app"),
  ("presentaciones", "Presentaciones programáticas"),
  ("reportes", "Reportes: HTML, PDF y Excel"),
  ("escritorio", "Escritorio"),
  ("cli-mas-alla-de-argparse", "CLI más allá de argparse"),
  ("rich-e-interaccion", "rich e interacción en terminal"),
  ("textual", "TUI completas con Textual"),
  ("veredicto", "Veredicto: prototipo o frontend")]),
 ("db", "Hablarle a cada sistema de datos", [
  ("el-db-api", "El panorama y el DB-API 2.0"),
  ("mysql-y-mariadb", "MySQL y MariaDB"),
  ("sql-server-y-oracle", "SQL Server y Oracle"),
  ("sqlite-a-fondo", "SQLite a fondo"),
  ("duckdb", "DuckDB"),
  ("valkey", "Clave-valor: Valkey"),
  ("mongodb", "Documental: MongoDB"),
  ("cassandra", "Columnar ancho: Cassandra y ScyllaDB"),
  ("neo4j", "Grafo: Neo4j"),
  ("series-de-tiempo", "Series de tiempo: TimescaleDB e InfluxDB"),
  ("vectorial", "Vectorial: pgvector y Qdrant"),
  ("busqueda", "Búsqueda: OpenSearch y Meilisearch"),
  ("objetos-s3", "Objetos: S3 y MinIO"),
  ("bitacora-de-eventos", "Bitácora de eventos: Kafka y NATS"),
  ("veredicto", "Veredicto: el árbol de decisión")]),
 ("jv", "Convivir con tu stack Java", [
  ("los-formatos-de-la-jvm", "Los formatos que la JVM ya produce"),
  ("jpype-y-py4j", "JPype y Py4J"),
  ("graalpy-y-jython", "GraalPy y Jython"),
  ("la-arquitectura-mixta", "La arquitectura mixta: dónde poner la frontera")]),
 ("so", "Optimización, simulación y decisiones", [
  ("describir-en-vez-de-programar", "Describir el problema en vez de programarlo"),
  ("programacion-lineal", "Programación lineal y entera"),
  ("or-tools", "OR-Tools y CP-SAT"),
  ("rutas-y-grafos", "Rutas y grafos"),
  ("simulacion-con-simpy", "Simulación de eventos discretos"),
  ("cuando-no-hay-modelo", "Cuando no hay modelo"),
  ("veredicto", "Veredicto: cuándo paga y cuándo bastaba la hoja")]),
 ("or", "ORMs y acceso a datos", [
  ("el-eje", "El eje: mapeo, constructor, SQL"),
  ("sqlalchemy-a-fondo", "SQLAlchemy a fondo"),
  ("active-record", "Active Record: Django ORM, Peewee, Piccolo"),
  ("pony", "Pony ORM: generadores a SQL"),
  ("los-asincronos", "Los ORM asíncronos"),
  ("sin-orm", "Sin ORM"),
  ("migraciones", "Migraciones fuera de Alembic"),
  ("veredicto", "Veredicto: la misma consulta en seis bibliotecas")]),
 ("vz", "Visualización y gráficos", [
  ("el-modelo-y-matplotlib", "El modelo y Matplotlib"),
  ("la-gramatica", "La gramática: Altair, plotnine, Great Tables"),
  ("graficos-que-no-son-datos", "Gráficos que no son datos"),
  ("el-grafico-que-miente", "Veredicto: el gráfico que miente")]),
 ("sy", "El sistema operativo y los procesos", [
  ("subprocess-a-fondo", "subprocess a fondo"),
  ("las-envolturas", "Las envolturas: plumbum, sh, invoke"),
  ("inspeccion-del-sistema", "Inspección del sistema"),
  ("el-sistema-de-archivos", "El sistema de archivos en serio"),
  ("reaccionar-a-cambios", "Reaccionar a cambios"),
  ("convivir-con-el-sistema", "Convivir con systemd"),
  ("sincronizacion-y-respaldo", "Sincronización y respaldo"),
  ("veredicto", "Veredicto: dónde deja de servir el script de shell")]),
 ("pr", "Protocolos y contratos más allá de REST", [
  ("el-eje", "El eje: contrato implícito, esquema, IDL"),
  ("grpc-y-protobuf", "gRPC y Protobuf"),
  ("formatos-binarios", "Los formatos binarios"),
  ("graphql", "GraphQL desde Python"),
  ("tiempo-real", "Tiempo real: WebSocket y SSE"),
  ("mensajeria-como-contrato", "Mensajería como contrato"),
  ("versionado-de-contratos", "Versionado y pruebas de contratos"),
  ("veredicto", "Veredicto: REST y las tres excepciones")]),
 ("pk", "El panorama de gestores y empaquetado", [
  ("el-modelo-real", "El modelo real de un entorno"),
  ("pip-venv-y-pip-tools", "pip, venv y pip-tools"),
  ("uv", "uv"),
  ("conda-y-compania", "conda, mamba y Miniforge"),
  ("poetry-y-pdm", "Poetry y PDM"),
  ("empaquetar-y-publicar", "Empaquetar y publicar"),
  ("entregar-a-quien-no-es-ingeniero", "Entregar a quien no es ingeniero"),
  ("veredicto", "Veredicto: uno, quince o una plataforma")]),
 ("ff", "La frontera nativa", [
  ("el-modelo", "El modelo: GIL y módulos de extensión"),
  ("ctypes-y-cffi", "ctypes y cffi"),
  ("cython", "Cython"),
  ("numba", "numba"),
  ("rust-y-cpp", "PyO3, pybind11 y nanobind"),
  ("el-buffer-compartido", "El buffer compartido y la copia cero"),
  ("paralelismo-real", "Paralelismo real: subintérpretes y sin GIL"),
  ("veredicto", "Veredicto: la misma función en cuatro fronteras")]),
 ("ar", "Archivos y multimedia", [
  ("binario-de-verdad", "Binario de verdad"),
  ("pillow", "Pillow"),
  ("opencv-y-svg", "OpenCV, scikit-image y SVG"),
  ("pdf", "PDF"),
  ("office", "Office: Word, Excel y PowerPoint"),
  ("markdown-html-y-pandoc", "Markdown, HTML y pandoc"),
  ("latex-y-typst", "LaTeX y Typst"),
  ("video", "Vídeo"),
  ("audio", "Audio"),
  ("veredicto", "Veredicto: el pegamento contra el binario")]),
 ("gi", "Geoespacial", [
  ("el-modelo", "El modelo: geometría, proyección, topología"),
  ("vectorial", "Vectorial: shapely, geopandas, pyproj"),
  ("postgis", "PostGIS desde Python"),
  ("raster", "Ráster y teledetección"),
  ("rutas-y-direcciones", "Rutas y direcciones"),
  ("mapas-como-entregable", "Mapas como entregable"),
  ("veredicto", "Veredicto: cuándo basta con lat y lon")]),
 ("cv", "Visión por computador", [
  ("el-modelo", "El modelo: píxeles, características, red"),
  ("deteccion", "Detección"),
  ("puntos-faciales", "Puntos de referencia faciales"),
  ("morphing", "Morphing desde cero"),
  ("reconocimiento", "Reconocimiento e identidad"),
  ("segmentacion-y-edicion", "Segmentación y edición"),
  ("video-con-modelos", "Vídeo con modelos"),
  ("veredicto", "Veredicto ético y legal")]),
 ("ed", "Didáctica, divulgación y juguetes", [
  ("turtle", "turtle"),
  ("juegos", "Juegos como vehículo"),
  ("notebooks-para-explicar", "Notebooks para explicar"),
  ("visualizar-algoritmos", "Visualizar algoritmos"),
  ("veredicto", "Veredicto: cuándo simplificar ayuda y cuándo miente")]),
]

def numerar():
    n = 0
    for tt, nombre, secs in CARTA:
        for i, (slug, titulo) in enumerate(secs, 1):
            n += 1
            yield n, tt, nombre, i, len(secs), slug, titulo, f"op{n:03d}-{tt}{i:02d}-{slug}.md"

if __name__ == "__main__":
    filas = list(numerar())
    print(len(filas))
