apiVersion: v1
kind: Service
metadata:
  name: storefront
  namespace: apps
  labels:
    app.kubernetes.io/name: storefront
    app.kubernetes.io/part-of: lab
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: storefront
  ports:
    - name: http
      port: 8080
      targetPort: http
